version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: deadstock-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-deadstock}
      MYSQL_USER: ${MYSQL_USER:-deadstock}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-deadstockpassword}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
volumes:
  db_data:
